### NOTE: To use this file VSC REST Client extension must be installed 

### Finds a Game by ID
GET http://localhost:5000/games/<id>

### Creates a Game
POST http://localhost:5000/games
Content-Type: application/json

{
    "name": "name",
    "mode": "mode"
}

### Starts a Game
PATCH http://localhost:5000/games/<id>/start

### Ends a Game
PATCH http://localhost:5000/games/<id>/end
Content-Type: application/json

{
    "winnerId": "winnerId"
}

### Joins a Game
PATCH http://localhost:5000/games/<id>/join
Content-Type: application/json

{
    "playerId": "playerId"
}